version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.7.1
    ports:
      - 9200:9200
    networks:
      - default-network
  
  rabbitmq:
    image: rabbitmq:3.7.14-alpine
    ports:
      - 5672:5672
    networks:
      - default-network

networks:
  default-network: